/// Flutter icons Bee
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bee
///      fonts:
///       - asset: fonts/Bee.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Bee {
  Bee._();

  static const _kFontFam = 'Bee';
  static const String? _kFontPkg = null;

  static const IconData bee = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
